 /******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM 
 *              Microcontroller - Port Driver
 *
 * Author: Mohamed Hisham
 ******************************************************************************/

#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

/* PB structure used with Port_Init API */
const Port_ConfigType Port_Configuration ={
  PORT_A_INDEX, PORT_A_PIN_0, PORT_A_PIN_0_DIR, PORT_A_PIN_0_DIR_CHANGEABLE, PORT_A_PIN_0_RESISTOR, PORT_A_PIN_0_VALUE, PORT_A_PIN_0_MODE, PORT_A_PIN_0_PCTL, PORT_A_PIN_0_MODE_CHANGEABLE,
  PORT_A_INDEX, PORT_A_PIN_1, PORT_A_PIN_1_DIR, PORT_A_PIN_1_DIR_CHANGEABLE, PORT_A_PIN_1_RESISTOR, PORT_A_PIN_1_VALUE, PORT_A_PIN_1_MODE, PORT_A_PIN_1_PCTL, PORT_A_PIN_1_MODE_CHANGEABLE,
  PORT_A_INDEX, PORT_A_PIN_2, PORT_A_PIN_2_DIR, PORT_A_PIN_2_DIR_CHANGEABLE, PORT_A_PIN_2_RESISTOR, PORT_A_PIN_2_VALUE, PORT_A_PIN_2_MODE, PORT_A_PIN_2_PCTL, PORT_A_PIN_2_MODE_CHANGEABLE,
  PORT_A_INDEX, PORT_A_PIN_3, PORT_A_PIN_3_DIR, PORT_A_PIN_3_DIR_CHANGEABLE, PORT_A_PIN_3_RESISTOR, PORT_A_PIN_3_VALUE, PORT_A_PIN_3_MODE, PORT_A_PIN_3_PCTL, PORT_A_PIN_3_MODE_CHANGEABLE,
  PORT_A_INDEX, PORT_A_PIN_4, PORT_A_PIN_4_DIR, PORT_A_PIN_4_DIR_CHANGEABLE, PORT_A_PIN_4_RESISTOR, PORT_A_PIN_4_VALUE, PORT_A_PIN_4_MODE, PORT_A_PIN_4_PCTL, PORT_A_PIN_4_MODE_CHANGEABLE,
  PORT_A_INDEX, PORT_A_PIN_5, PORT_A_PIN_5_DIR, PORT_A_PIN_5_DIR_CHANGEABLE, PORT_A_PIN_5_RESISTOR, PORT_A_PIN_5_VALUE, PORT_A_PIN_5_MODE, PORT_A_PIN_5_PCTL, PORT_A_PIN_5_MODE_CHANGEABLE,
  PORT_A_INDEX, PORT_A_PIN_6, PORT_A_PIN_6_DIR, PORT_A_PIN_6_DIR_CHANGEABLE, PORT_A_PIN_6_RESISTOR, PORT_A_PIN_6_VALUE, PORT_A_PIN_6_MODE, PORT_A_PIN_6_PCTL, PORT_A_PIN_6_MODE_CHANGEABLE,
  PORT_A_INDEX, PORT_A_PIN_7, PORT_A_PIN_7_DIR, PORT_A_PIN_7_DIR_CHANGEABLE, PORT_A_PIN_7_RESISTOR, PORT_A_PIN_7_VALUE, PORT_A_PIN_7_MODE, PORT_A_PIN_7_PCTL, PORT_A_PIN_7_MODE_CHANGEABLE,
  
  PORT_B_INDEX, PORT_B_PIN_0, PORT_B_PIN_0_DIR, PORT_B_PIN_0_DIR_CHANGEABLE, PORT_B_PIN_0_RESISTOR, PORT_B_PIN_0_VALUE, PORT_B_PIN_0_MODE, PORT_B_PIN_0_PCTL, PORT_B_PIN_0_MODE_CHANGEABLE,
  PORT_B_INDEX, PORT_B_PIN_1, PORT_B_PIN_1_DIR, PORT_B_PIN_1_DIR_CHANGEABLE, PORT_B_PIN_1_RESISTOR, PORT_B_PIN_1_VALUE, PORT_B_PIN_1_MODE, PORT_B_PIN_1_PCTL, PORT_B_PIN_1_MODE_CHANGEABLE,
  PORT_B_INDEX, PORT_B_PIN_2, PORT_B_PIN_2_DIR, PORT_B_PIN_2_DIR_CHANGEABLE, PORT_B_PIN_2_RESISTOR, PORT_B_PIN_2_VALUE, PORT_B_PIN_2_MODE, PORT_B_PIN_2_PCTL, PORT_B_PIN_2_MODE_CHANGEABLE,
  PORT_B_INDEX, PORT_B_PIN_3, PORT_B_PIN_3_DIR, PORT_B_PIN_3_DIR_CHANGEABLE, PORT_B_PIN_3_RESISTOR, PORT_B_PIN_3_VALUE, PORT_B_PIN_3_MODE, PORT_B_PIN_3_PCTL, PORT_B_PIN_3_MODE_CHANGEABLE,
  PORT_B_INDEX, PORT_B_PIN_4, PORT_B_PIN_4_DIR, PORT_B_PIN_4_DIR_CHANGEABLE, PORT_B_PIN_4_RESISTOR, PORT_B_PIN_4_VALUE, PORT_B_PIN_4_MODE, PORT_B_PIN_4_PCTL, PORT_B_PIN_4_MODE_CHANGEABLE,
  PORT_B_INDEX, PORT_B_PIN_5, PORT_B_PIN_5_DIR, PORT_B_PIN_5_DIR_CHANGEABLE, PORT_B_PIN_5_RESISTOR, PORT_B_PIN_5_VALUE, PORT_B_PIN_5_MODE, PORT_B_PIN_5_PCTL, PORT_B_PIN_5_MODE_CHANGEABLE,
  PORT_B_INDEX, PORT_B_PIN_6, PORT_B_PIN_6_DIR, PORT_B_PIN_6_DIR_CHANGEABLE, PORT_B_PIN_6_RESISTOR, PORT_B_PIN_6_VALUE, PORT_B_PIN_6_MODE, PORT_B_PIN_6_PCTL, PORT_B_PIN_6_MODE_CHANGEABLE,
  PORT_B_INDEX, PORT_B_PIN_7, PORT_B_PIN_7_DIR, PORT_B_PIN_7_DIR_CHANGEABLE, PORT_B_PIN_7_RESISTOR, PORT_B_PIN_7_VALUE, PORT_B_PIN_7_MODE, PORT_B_PIN_7_PCTL, PORT_B_PIN_7_MODE_CHANGEABLE,
  
  PORT_C_INDEX, PORT_C_PIN_0, PORT_C_PIN_0_DIR, PORT_C_PIN_0_DIR_CHANGEABLE, PORT_C_PIN_0_RESISTOR, PORT_C_PIN_0_VALUE, PORT_C_PIN_0_MODE, PORT_C_PIN_0_PCTL, PORT_C_PIN_0_MODE_CHANGEABLE,
  PORT_C_INDEX, PORT_C_PIN_1, PORT_C_PIN_1_DIR, PORT_C_PIN_1_DIR_CHANGEABLE, PORT_C_PIN_1_RESISTOR, PORT_C_PIN_1_VALUE, PORT_C_PIN_1_MODE, PORT_C_PIN_1_PCTL, PORT_C_PIN_1_MODE_CHANGEABLE,
  PORT_C_INDEX, PORT_C_PIN_2, PORT_C_PIN_2_DIR, PORT_C_PIN_2_DIR_CHANGEABLE, PORT_C_PIN_2_RESISTOR, PORT_C_PIN_2_VALUE, PORT_C_PIN_2_MODE, PORT_C_PIN_2_PCTL, PORT_C_PIN_2_MODE_CHANGEABLE,
  PORT_C_INDEX, PORT_C_PIN_3, PORT_C_PIN_3_DIR, PORT_C_PIN_3_DIR_CHANGEABLE, PORT_C_PIN_3_RESISTOR, PORT_C_PIN_3_VALUE, PORT_C_PIN_3_MODE, PORT_C_PIN_3_PCTL, PORT_C_PIN_3_MODE_CHANGEABLE,
  PORT_C_INDEX, PORT_C_PIN_4, PORT_C_PIN_4_DIR, PORT_C_PIN_4_DIR_CHANGEABLE, PORT_C_PIN_4_RESISTOR, PORT_C_PIN_4_VALUE, PORT_C_PIN_4_MODE, PORT_C_PIN_4_PCTL, PORT_C_PIN_4_MODE_CHANGEABLE,
  PORT_C_INDEX, PORT_C_PIN_5, PORT_C_PIN_5_DIR, PORT_C_PIN_5_DIR_CHANGEABLE, PORT_C_PIN_5_RESISTOR, PORT_C_PIN_5_VALUE, PORT_C_PIN_5_MODE, PORT_C_PIN_5_PCTL, PORT_C_PIN_5_MODE_CHANGEABLE,
  PORT_C_INDEX, PORT_C_PIN_6, PORT_C_PIN_6_DIR, PORT_C_PIN_6_DIR_CHANGEABLE, PORT_C_PIN_6_RESISTOR, PORT_C_PIN_6_VALUE, PORT_C_PIN_6_MODE, PORT_C_PIN_6_PCTL, PORT_C_PIN_6_MODE_CHANGEABLE,
  PORT_C_INDEX, PORT_C_PIN_7, PORT_C_PIN_7_DIR, PORT_C_PIN_7_DIR_CHANGEABLE, PORT_C_PIN_7_RESISTOR, PORT_C_PIN_7_VALUE, PORT_C_PIN_7_MODE, PORT_C_PIN_7_PCTL, PORT_C_PIN_7_MODE_CHANGEABLE,
  
  PORT_D_INDEX, PORT_D_PIN_0, PORT_D_PIN_0_DIR, PORT_D_PIN_0_DIR_CHANGEABLE, PORT_D_PIN_0_RESISTOR, PORT_D_PIN_0_VALUE, PORT_D_PIN_0_MODE, PORT_D_PIN_0_PCTL, PORT_D_PIN_0_MODE_CHANGEABLE,
  PORT_D_INDEX, PORT_D_PIN_1, PORT_D_PIN_1_DIR, PORT_D_PIN_1_DIR_CHANGEABLE, PORT_D_PIN_1_RESISTOR, PORT_D_PIN_1_VALUE, PORT_D_PIN_1_MODE, PORT_D_PIN_1_PCTL, PORT_D_PIN_1_MODE_CHANGEABLE,
  PORT_D_INDEX, PORT_D_PIN_2, PORT_D_PIN_2_DIR, PORT_D_PIN_2_DIR_CHANGEABLE, PORT_D_PIN_2_RESISTOR, PORT_D_PIN_2_VALUE, PORT_D_PIN_2_MODE, PORT_D_PIN_2_PCTL, PORT_D_PIN_2_MODE_CHANGEABLE,
  PORT_D_INDEX, PORT_D_PIN_3, PORT_D_PIN_3_DIR, PORT_D_PIN_3_DIR_CHANGEABLE, PORT_D_PIN_3_RESISTOR, PORT_D_PIN_3_VALUE, PORT_D_PIN_3_MODE, PORT_D_PIN_3_PCTL, PORT_D_PIN_3_MODE_CHANGEABLE,
  PORT_D_INDEX, PORT_D_PIN_4, PORT_D_PIN_4_DIR, PORT_D_PIN_4_DIR_CHANGEABLE, PORT_D_PIN_4_RESISTOR, PORT_D_PIN_4_VALUE, PORT_D_PIN_4_MODE, PORT_D_PIN_4_PCTL, PORT_D_PIN_4_MODE_CHANGEABLE,
  PORT_D_INDEX, PORT_D_PIN_5, PORT_D_PIN_5_DIR, PORT_D_PIN_5_DIR_CHANGEABLE, PORT_D_PIN_5_RESISTOR, PORT_D_PIN_5_VALUE, PORT_D_PIN_5_MODE, PORT_D_PIN_5_PCTL, PORT_D_PIN_5_MODE_CHANGEABLE,
  PORT_D_INDEX, PORT_D_PIN_6, PORT_D_PIN_6_DIR, PORT_D_PIN_6_DIR_CHANGEABLE, PORT_D_PIN_6_RESISTOR, PORT_D_PIN_6_VALUE, PORT_D_PIN_6_MODE, PORT_D_PIN_6_PCTL, PORT_D_PIN_6_MODE_CHANGEABLE,
  PORT_D_INDEX, PORT_D_PIN_7, PORT_D_PIN_7_DIR, PORT_D_PIN_7_DIR_CHANGEABLE, PORT_D_PIN_7_RESISTOR, PORT_D_PIN_7_VALUE, PORT_D_PIN_7_MODE, PORT_D_PIN_7_PCTL, PORT_D_PIN_7_MODE_CHANGEABLE,
  
  PORT_E_INDEX, PORT_E_PIN_0, PORT_E_PIN_0_DIR, PORT_E_PIN_0_DIR_CHANGEABLE, PORT_E_PIN_0_RESISTOR, PORT_E_PIN_0_VALUE, PORT_E_PIN_0_MODE, PORT_E_PIN_0_PCTL, PORT_E_PIN_0_MODE_CHANGEABLE,
  PORT_E_INDEX, PORT_E_PIN_1, PORT_E_PIN_1_DIR, PORT_E_PIN_1_DIR_CHANGEABLE, PORT_E_PIN_1_RESISTOR, PORT_E_PIN_1_VALUE, PORT_E_PIN_1_MODE, PORT_E_PIN_1_PCTL, PORT_E_PIN_1_MODE_CHANGEABLE,
  PORT_E_INDEX, PORT_E_PIN_2, PORT_E_PIN_2_DIR, PORT_E_PIN_2_DIR_CHANGEABLE, PORT_E_PIN_2_RESISTOR, PORT_E_PIN_2_VALUE, PORT_E_PIN_2_MODE, PORT_E_PIN_2_PCTL, PORT_E_PIN_2_MODE_CHANGEABLE,
  PORT_E_INDEX, PORT_E_PIN_3, PORT_E_PIN_3_DIR, PORT_E_PIN_3_DIR_CHANGEABLE, PORT_E_PIN_3_RESISTOR, PORT_E_PIN_3_VALUE, PORT_E_PIN_3_MODE, PORT_E_PIN_3_PCTL, PORT_E_PIN_3_MODE_CHANGEABLE,
  PORT_E_INDEX, PORT_E_PIN_4, PORT_E_PIN_4_DIR, PORT_E_PIN_4_DIR_CHANGEABLE, PORT_E_PIN_4_RESISTOR, PORT_E_PIN_4_VALUE, PORT_E_PIN_4_MODE, PORT_E_PIN_4_PCTL, PORT_E_PIN_4_MODE_CHANGEABLE,
  PORT_E_INDEX, PORT_E_PIN_5, PORT_E_PIN_5_DIR, PORT_E_PIN_5_DIR_CHANGEABLE, PORT_E_PIN_5_RESISTOR, PORT_E_PIN_5_VALUE, PORT_E_PIN_5_MODE, PORT_E_PIN_5_PCTL, PORT_E_PIN_5_MODE_CHANGEABLE,
  
  PORT_F_INDEX, PORT_F_PIN_0, PORT_F_PIN_0_DIR, PORT_F_PIN_0_DIR_CHANGEABLE, PORT_F_PIN_0_RESISTOR, PORT_F_PIN_0_VALUE, PORT_F_PIN_0_MODE, PORT_F_PIN_0_PCTL, PORT_F_PIN_0_MODE_CHANGEABLE,
  PORT_F_INDEX, PORT_F_PIN_1, PORT_F_PIN_1_DIR, PORT_F_PIN_1_DIR_CHANGEABLE, PORT_F_PIN_1_RESISTOR, PORT_F_PIN_1_VALUE, PORT_F_PIN_1_MODE, PORT_F_PIN_1_PCTL, PORT_F_PIN_1_MODE_CHANGEABLE,
  PORT_F_INDEX, PORT_F_PIN_2, PORT_F_PIN_2_DIR, PORT_F_PIN_2_DIR_CHANGEABLE, PORT_F_PIN_2_RESISTOR, PORT_F_PIN_2_VALUE, PORT_F_PIN_2_MODE, PORT_F_PIN_2_PCTL, PORT_F_PIN_2_MODE_CHANGEABLE,
  PORT_F_INDEX, PORT_F_PIN_3, PORT_F_PIN_3_DIR, PORT_F_PIN_3_DIR_CHANGEABLE, PORT_F_PIN_3_RESISTOR, PORT_F_PIN_3_VALUE, PORT_F_PIN_3_MODE, PORT_F_PIN_3_PCTL, PORT_F_PIN_3_MODE_CHANGEABLE,
  PORT_F_INDEX, PORT_F_PIN_4, PORT_F_PIN_4_DIR, PORT_F_PIN_4_DIR_CHANGEABLE, PORT_F_PIN_4_RESISTOR, PORT_F_PIN_4_VALUE, PORT_F_PIN_4_MODE, PORT_F_PIN_4_PCTL, PORT_F_PIN_4_MODE_CHANGEABLE,
};